### PR TITLE
Added default toml to correct failed build during first tutorial step

### PR DESCRIPTION
**Pull request by eeyun**
Signed-off-by: Ian Henry <ihenry@chef.io>

### CODE REVIEW

**Comment by eeyun** [comment]
https://github.com/habitat-sh/habitat-example-plans/issues/11

**Comment by mwrock** [comment]
The tutorial used to work without a default.toml but that changed with recent config related enhancements. I think adding this toml is the right thin but we will want to remove step #1 from the bottom of https://www.habitat.sh/tutorials/getting-started/linux/configure-plan/ as well.

**Comment by mwrock** [comment]
oh right! different repos...cool.

**Comment by mwrock** [comment]
@thesentinels approve

**Pull request merged**
