### PR TITLE
`pkg_source` is required

### PR DESCRIPTION
**Pull request by nathenharvey**
The `pkg_source` is now required in the `plan.sh`.

With `do_download()` overridden, this will not be used but is still
required.

An alternate value might be something like `nosuchfile.tar.gz`

Signed-off-by: Nathen Harvey <nharvey@chef.io>

### CODE REVIEW

**Comment by davidwrede** [comment]
I like the alternate approach of using `nosuchfile.tar.gz`. I'll submit and push that change through today.

**Comment by nathenharvey** [comment]
my reasoning behind providing the github repo was that this info is still helpful to consumers of the package.  For example, the `pkg_source` is visible on in app.habitat.sh.  Although it's not actually used during the download phase, it's a good practice (IMHO) to provide that bit of metadata for a package.

Either way is fine with me but that may provide a bit more context for the change.

**Comment by davidwrede** [comment]
Agree on needing to provide metadata. I think I'll use `pkg_upstream_url` since it's strictly a metadata setting. IMHO, setting `pkg_source` to a resolvable value implies that we are going to download something and then take some sort of action on it.

**Comment by nathenharvey** [comment]
yes!  awesome, I didn't know about `pkg_upstream_url`  I can update this PR.

**Comment by davidwrede** [comment]
Change looks good. Thanks @nathenharvey!

**Pull request merged**
